name: Autorestart
version: ${project.version}
main: net.nebulabc.autorestart.Autorestart
api-version: 1.17
authors: [ NebulaBC ]
description: An Auto-restart plugin for Spigot Minecraft
website: nebulabc.net
